version: 0.0
os: linux
files:
  - source: /
    destination: /app
file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 300
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 420
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 300
