version: 0.2
env:
  variables:
    COMMIT_HASH: $(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    IMAGE_TAG: $(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
    IMAGE_URI: 575950973345.dkr.ecr.us-east-1.amazonaws.com/react-tester
    VERSION: V7
    REGION : us-east-1
    USERNAME: AWS
    DOCKER_USERNAME: 'kenphetmany'
    DOCKER_PASSWORD: '*8QGDHwBe$6nH3'

phases:
  pre_build:
    commands:
      - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - IMAGE_URI=public.ecr.aws/q7m2t9t6
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - echo COMMIT_HASH - $COMMIT_HASH
      - echo IMAGE_URI - $IMAGE_URI
      - echo IMAGE_TAG - $IMAGE_TAG
      - echo CONTAINER_NAME - $ecs_container_name
      - aws --version
      - aws ecr-public get-login-password --region $REGION | docker login --username $USERNAME --password-stdin $IMAGE_URI
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker compose -f docker-compose.prod.yml build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker compose -f docker-compose.prod.yml push
      - printf '[{"name":"testContainer","imageUri":"%s"}]' $$IMAGE_URI:$VERSION > imagedefinitions.json
artifacts:
  files:
  - tasksdefinitions.json
  - imagedefinitions.json
