version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password | docker login --username AWS --password-stdin 575950973345.dkr.ecr.us-east-1.amazonaws.com/react-tester
      - REPOSITORY_URI=575950973345.dkr.ecr.us-east-1.amazonaws.com/react-tester
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker compose -f docker-compose.dev.yml build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker compose -f docker-compose.dev.yml push
artifacts:
  files:
  - "**/*"