version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/q7m2t9t6
      - REPOSITORY_URI=public.ecr.aws/q7m2t9t6/testing
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker compose -f docker-compose.prod.yml build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker compose -f docker-compose.prod.yml push
artifacts:
  files:
  - "**/*"